### ISSUE TITLE
Distribution of fragment length not working?

### ISSUE THREAD

**Issue by mengzhou** [smithlabcode/walt#20]
I'm using the latest version of walt. The mapstats file does have this section, but there is no content.

**Comment by acgtun** [comment]
In this case, most probably the job was not successfully completed.

**Comment by acgtun** [comment]
Hi, Meng,

Thanks for reporting this issue. There are several cases. (1) If there is no mapstats file, it most probably, the job was not successfully competed. It means that the program stopped incorrectly. (2) As you said, there is a mapstats file, but it's empty. Is that right? However, generally, I don't think you were in this case. We can talk later about this.

Best,
Haifeng

**Comment by acgtun** [comment]
HI, Meng,

When output MR format results, there was bug which lea to no fragment length distribution in the mapstats file. I update the code. Please git pull it. Thanks for reporting this.

Best,
Haifeng
