### ISSUE TITLE
Adding robustness in OptionParser for specifying options more than once

### ISSUE THREAD

**Issue by andrewdavidsmith** [smithlabcode/walt#21]
Users can accidentally specify command line options more than once. If "leftover_args" are not properly processed, such as checking for their existence, then such user accidents may "shift" the values of all parameters later. Example:
`> ./walt -i hg19_walt.dbindex -1 a.fq -2 b.fq -o c.out -C GATCGGAAGAGCG -C -t 8 -m 10`
In a case like this it appears the `-C` value will be over-written, and the extra `8` on the command line will ignored. Consider something like the following:
```C++
if (!leftover_args.empty()) {
    cerr << opt_parse.help_message() << endl;
    return EXIT_SUCCESS;
}
```
This kind of check is used in most programs using the OptionParser class in smithlab_cpp. It does not perfectly solve all types of problems, but it catches many.

**Comment by acgtun** [comment]
Thanks. This is very good suggestion.
