### ISSUE TITLE
average and standard deviation of insert size for paired end reads

### ISSUE THREAD

**Issue by bdecato** [smithlabcode/walt#22]
Printing the average and standard deviation insert size for paired end mapped reads in the .mapstats file would be incredibly helpful: these statistics are required for the GEO submission form, and I just found myself in a situation where I had to compute them from the distribution, so I approximated with the mode fragment length.

**Comment by acgtun** [comment]
Hi, Ben,

Thank you very much for you suggestion.

I just pushed a new commit with the average and standard deviation of fragment lengths.
If you find anything wrong, please let me know.

Thanks again.

Best,
Haifeng
