### ISSUE TITLE
indexing for non-human (HIV) genome

### ISSUE THREAD

**Issue by antoine4ucsd** [smithlabcode/walt#26]
Hi,
I am trying to map paired end fastq files from bisulfite HIV LTR. Therefore, the mapping step implies using the HIV LTR region as a reference and not the human genome
I tried to create a ref.dbindex from my ref.fa file but it does not really make sense to me:

`makedb -c ./reference -o ref.dbindex
[IDENTIFYING CHROMS] [DONE]
chromosome files found (approx size):
./reference/ref.fa (0.00Mbp)
[BIULD INDEX FOR FORWARD STRAND (C->T)]
[READING CHROMOSOMES]
[THERE ARE 1 CHROMOSOMES IN THE GENOME]
[THE TOTAL LENGTH OF ALL CHROMOSOMES IS 352]
[COUNT BUCKET SIZE]
[HASH TO BUCKET]
[SORTING BUCKETS FOR HASH TABLE]
[WRITTING INDEX TO ref.dbindex_CT00]
[BIULD INDEX FOR REVERSE STRAND (C->T)]
[READING CHROMOSOMES]
[THERE ARE 1 CHROMOSOMES IN THE GENOME]
[THE TOTAL LENGTH OF ALL CHROMOSOMES IS 352]
[COUNT BUCKET SIZE]
[HASH TO BUCKET]
[SORTING BUCKETS FOR HASH TABLE]
[WRITTING INDEX TO ref.dbindex_CT01]
[BIULD INDEX FOR FORWARD STRAND (G->A)]
[READING CHROMOSOMES]
[THERE ARE 1 CHROMOSOMES IN THE GENOME]
[THE TOTAL LENGTH OF ALL CHROMOSOMES IS 352]
[COUNT BUCKET SIZE]
[HASH TO BUCKET]
[SORTING BUCKETS FOR HASH TABLE]
[WRITTING INDEX TO ref.dbindex_GA10]
[BIULD INDEX FOR REVERSE STRAND (G->A)]
[READING CHROMOSOMES]
[THERE ARE 1 CHROMOSOMES IN THE GENOME]
[THE TOTAL LENGTH OF ALL CHROMOSOMES IS 352]
[COUNT BUCKET SIZE]
[HASH TO BUCKET]
[SORTING BUCKETS FOR HASH TABLE]
[WRITTING INDEX TO ref.dbindex_GA11]
[READING CHROMOSOMES]
[THERE ARE 1 CHROMOSOMES IN THE GENOME]
[THE TOTAL LENGTH OF ALL CHROMOSOMES IS 352]
[WRITTING INDEX HEAD TO ref.dbindex]`

It does generate the following files:
ref.dbindex
ref.dbindex_CT00
ref.dbindex_CT01
ref.dbindex_GA10
ref.dbindex_GA11

When I try to map my paired end reads to this indexed ref,  it yelds to >99.9% unmapped reads... My guess is that it has to do with the indexing. 

`walt -i ./reference_notconverted/ref.dbindex -1 SAMPLE_R1_trimmed.fq -2 SAMPLE_R2_trimmed.fq -o C1WALT.sam`
I am attaching the ref genome (bisulfite converted or not)

[HIVLTR_BISUFITE.txt](https://github.com/smithlabcode/walt/files/1334270/HIVLTR_BISUFITE.txt)
[HIVLTR.txt](https://github.com/smithlabcode/walt/files/1334273/HIVLTR.txt)

All suggestions are welcome?
thanks !
a

**Comment by acgtun** [comment]
Hi antoine4ucsd,
I saw your reference is pretty short. Could you give us some examples of your reads? Thanks.

**Comment by antoine4ucsd** [comment]
May I share a couple of fastq files via googledrive or dropbox?
thanks!
a

**Comment by acgtun** [comment]
sure

**Comment by antoine4ucsd** [comment]
This link should work in a couple of minutes (uploading)
https://www.dropbox.com/sh/x2dvvz1qwo3q7f4/AACENDHnbecXvi8_kkMPPHIEa?dl=0

let me know if it does not work and thanks in advance!
a

**Comment by antoine4ucsd** [comment]
done

**Comment by acgtun** [comment]
seems your reads is 1/4 length of the genome.
Are you sure the reads are generated from the genome you showed us?

**Comment by antoine4ucsd** [comment]
these should be paired end reads but I was expecting 200-300 bp reads

**Comment by antoine4ucsd** [comment]
the region covered is the bisulfite LTR (352 bp)

**Comment by acgtun** [comment]
but the total length of genome is only 352

**Comment by acgtun** [comment]
do the reads from this region?

**Comment by antoine4ucsd** [comment]
Yes 

Thanks,
a

**Comment by antoine4ucsd** [comment]
Yes - the reads should map the 352bp ref

Thanks,
a

**Comment by mengzhou** [comment]
Hi Antoine,

I tried bismark using bowtie2, and there was also nearly no mappable reads.
I suggest checking your reads, because after trimming the first 30 bp from
the 5' end for each read, I got slightly more mapped.


Best regards,
Meng

**Comment by antoine4ucsd** [comment]
thanks for your help!
Would you suggest more trimming? Can you share the way you tried with bismark and bowtie2  (command lines)?
Did you use the bisulfite converted genome as the ref?
I did have some more mapped results with bwa but not great anyway

thanks++ 
a

**Comment by mengzhou** [comment]
I used all default parameters with bismark, and it did bisulfite conversion
on the reference. My point is, if multiple mappers have similar results, it
probably means this is not a technical problem.


Best regards,
Meng

**Comment by antoine4ucsd** [comment]
Agree
thanks again for your responsiveness

**Comment by antoine4ucsd** [comment]
Hi 
I wanted to keep you updated about my exploratory analyses of the HIV LTR regions.
While the sequencing has a lot of room for improvement, I was finally able to map the (short) reads to the bisulfite conversion of the reference using the standard params of Bowtie2 and the GUI software UGENE...
The link below contains the bam output from the raw fq files and from the trimmed fq files mapped to the ref.
Next I created the mr file with the following:
`/to-mr -s 0 -o UGENE_C1bowtie2.mr -m general UGENE_C1bowtie2.sam.bam_sorted.bam LC_ALL=C sort -k 1,1 -k 2,2n -k 3,3n -k 6,6`
It seems to work properly.
Although I sorted the bam file, I have the following error ('notp properly sorted') while running the duplicate remover:

`duplicate-remover -S UGENE_C1bowtie2_stat.txt -o UGENE_C1bowtie2.mr.drmove UGENE_C1bowtie2.mr
input not properly sorted:`

I tried to move on for the bsrate but I am not sure how to deal with non-human genome ref:
I execute the following where ref is the name of my reference and ./reference is a folder containing the ref (previously processed with makedb):

`bsrate –c ./reference –N  –o UGENE_C1bowtie2.mr.bsrate UGENE_C1bowtie2.mr
required argument missing: [-c, -chrom]`
or

`bsrate –c ref –N  –o UGENE_C1bowtie2.mr.bsrate UGENE_C1bowtie2.mr
required argument missing: [-c, -chrom]`



Would you have any advice?
any chance methylkit R package can accept my input data although they were not processed with bismark? any alternative package?

thanks again in advance for your advices.

https://www.dropbox.com/sh/m01rkcu8mzv4nz4/AABIR6vsl53xm_KQsbbtHNA-a?dl=0

**Comment by andrewdavidsmith** [comment]
This is not the place to keep us updated. Please contact the methpipe google group for that.

On Sep 27, 2017, at 7:38 AM, antoine <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi
I wanted to keep you updated about my exploratory analyses of the HIV LTR regions.
While the sequencing has a lot of room for improvement, I was finally able to map the (short) reads to the bisulfite conversion of the reference using the standard params of Bowtie2 and the GUI software UGENE...
The link below contains the bam output from the raw fq files and from the trimmed fq files mapped to the ref.
Next I created the mr file with the following:
/to-mr -s 0 -o UGENE_C1bowtie2.mr -m general UGENE_C1bowtie2.sam.bam_sorted.bam LC_ALL=C sort -k 1,1 -k 2,2n -k 3,3n -k 6,6
It seems to work properly.
Although I sorted the bam file, I have the following error ('notp properly sorted') while running the duplicate remover:

duplicate-remover -S UGENE_C1bowtie2_stat.txt -o UGENE_C1bowtie2.mr.drmove UGENE_C1bowtie2.mr input not properly sorted:

I tried to move on for the bsrate but I am not sure how to deal with non-human genome ref:
I execute the following where ref is the name of my reference and ./reference is a folder containing the ref (previously processed with makedb):

bsrate –c ./reference –N –o UGENE_C1bowtie2.mr.bsrate UGENE_C1bowtie2.mr required argument missing: [-c, -chrom]
or

bsrate –c ref –N –o UGENE_C1bowtie2.mr.bsrate UGENE_C1bowtie2.mr required argument missing: [-c, -chrom]

Would you have any advice?
any chance methylkit R package can accept my input data although they were not processed with bismark? any alternative package?

thanks again in advance for your advices.

https://www.dropbox.com/sh/m01rkcu8mzv4nz4/AABIR6vsl53xm_KQsbbtHNA-a?dl=0<https://urldefense.proofpoint.com/v2/url?u=https-3A__www.dropbox.com_sh_m01rkcu8mzv4nz4_AABIR6vsl53xm-5FKQsbbtHNA-2Da-3Fdl-3D0&d=DwMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=2ti3K9K1XjkPszCPHB82Aw&m=Ps8HwkoLGJhZPIgedUF1ZSiHJw-JNKITNDYNdyyObEk&s=t3pTlIee1yo4xwLL0bk_VtUQLKNSEFmOCKbofcX9gqA&e=>

**Comment by antoine4ucsd** [comment]
oh, sorry.
I will move it to the methpipe group.
thanks again for your support
a
