### ISSUE TITLE
Error when mapping pair-end data

### ISSUE THREAD

**Issue by mengzhou** [smithlabcode/walt#27]
Got this error "The number of reads in paired-end files should be the same" which corresponds to [this](https://github.com/smithlabcode/walt/blob/master/src/walt/paired.cpp#L765).

I don't think there is a logic error in the codes, instead I suspect it is caused by the openmp, because this error only occurred when using multiple threads for mapping. This error often occurs when the mapping job is close to finish (after tens of hours), therefore now it is not easy to reproduce it.

Here's my guess about the cause. @acgtun please let me know if this is possible.
The function that updates the read number variable is `LoadReadsFromFastqFile` ([link to code](https://github.com/smithlabcode/walt/blob/master/src/walt/mapping.cpp#L33)), and it passes a reference of `num_of_reads`. There's another variable `n_reads_to_process` which tells the program how many reads to process at each for loop. Usually this is set to 1 million, or 500k. Could it be that at the last loop, when some mapping threads have started earlier than others, and loaded the remaining reads (less than 1 million), and `num_of_reads` was updated according to this number, but then this number was compared with the other thread at the previous loop.

**Comment by acgtun** [comment]
@mengzhou Hi Meng, Thanks for taking time to look into this.

I think the parallel is only for loop [PairEndMapping] (https://github.com/smithlabcode/walt/blob/24cfbabdc0b63bfd8def347a40411928fcd3f623/src/walt/paired.cpp#L755)
`#pragma omp parallel for
        for (uint32_t j = 0; j < num_of_reads[pi]; ++j) {
          PairEndMapping(read_seqs[pi][j], genome, hash_table, strand,
                         AG_WILDCARD, max_mismatches, b, top_results[pi][j],
                         stat_single_reads);
        }`

and `if (num_of_reads[0] != num_of_reads[1]) {` is out of that loop. 

If I am wrong, please point out. I haven't touched openmp for a long time. Thanks.

**Comment by acgtun** [comment]
we could try to add 
**#pragma omp barrier**
at the end of this line
https://github.com/smithlabcode/walt/blob/24cfbabdc0b63bfd8def347a40411928fcd3f623/src/walt/paired.cpp#L760

**Comment by mengzhou** [comment]
Recently I got two more errors with different values:
> num_of_reads[0] = 100000; num_of_reads[1] = 1324
> num_of_reads[0] = 4812; num_of_reads[1] = 100000
I will try adding the omp barrier line to see if it solves this problem.

**Comment by acgtun** [comment]
@mengzhou thanks Meng.

**Comment by jqujqu** [comment]
Tested with default N value and finished without error after adding the omp
barrier.

On Thu, Nov 16, 2017 at 1:00 PM, Haifeng Chen <notifications@github.com>
wrote:

> @mengzhou
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mengzhou&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=2THa9gRjvGUBof5MuD0aGQ&m=1X5ZUx_TfTvFjgGHQr35E2xhbr82pMVDlyY01LKovpk&s=Wx8ukA7uHS7gCDejjKzxprxx31quVSPGAKpyQ4ne16g&e=>
> thanks Meng.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_smithlabcode_walt_issues_27-23issuecomment-2D345060881&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=2THa9gRjvGUBof5MuD0aGQ&m=1X5ZUx_TfTvFjgGHQr35E2xhbr82pMVDlyY01LKovpk&s=F3BZOyJxX6jgynT7ZJ9TW_fHIqT8vgNvzf0vihXFoRU&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AHBggZAjZ6ShCknigWEhQWkCSsD7EogEks5s3KJ5gaJpZM4QL7gc&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=2THa9gRjvGUBof5MuD0aGQ&m=1X5ZUx_TfTvFjgGHQr35E2xhbr82pMVDlyY01LKovpk&s=nmjzAro5-3Pw6dUGAuv3W52PArAG96n6hM2iSawEDes&e=>
> .
>



-- 
Jenny

**Comment by acgtun** [comment]
@jqujqu thanks Jenny.
