### ISSUE TITLE
git clone

### ISSUE THREAD

**Issue by pawatmwit** [smithlabcode/walt#28]
hello, I think there is a typo in the readme. When I tried `git clone git@github.com:smithlabcode/walt.git`, it gave some sort of an authentication error. However, when I tried `git clone https://github.com/smithlabcode/walt.git` instead, it worked just fine...
Thanks!

**Comment by acgtun** [comment]
Hi pawatmwit, thanks for your interests in WALT. Github supports different ways to clone repos. To clone repos use git@github.com, you need setup SSH key.
https://help.github.com/articles/which-remote-url-should-i-use/

**Comment by pawatmwit** [comment]
Ahh I see. thanks!
